plugins {
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
    id 'maven-publish'
}

configurations {
    runtimeClasspath.extendsFrom(localRuntime)
}

neoForge {
    version = neo_version
    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }
    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    unitTest {
        enable()
        testedMod = mods."${mod_id}"
    }
}

dependencies {
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge-api:${jei_version}"
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}"
    localRuntime "mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = "drinkbeer-refill-${minecraft_version}-neoforge"
            from components.java
        }
    }
    repositories {
        maven {
            name = 'DragonsPlus'
            url = uri('https://maven.dragons.plus/releases')
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

publishMods {
    file = tasks.jar.archiveFile
    additionalFiles.from tasks.sourcesJar.archiveFile
    changelog = rootProject.file('CHANGELOG.md').text
    version = project.version
    type = BETA
    displayName = "Drink Beer Refill ${mod_version} for ${minecraft_version} (NeoForge)"
    modLoaders.add('neoforge')

    curseforge {
        projectId = curseforge_project_id
        accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
        minecraftVersions.add(minecraft_version)
        client = true
        server = true
    }

    modrinth {
        projectId = modrinth_project_id
        accessToken = providers.environmentVariable('MODRINTH_TOKEN')
        minecraftVersions.add(minecraft_version)
    }
}
